### PR TITLE
Westend Collectives chain spec

### PR DESCRIPTION
**Pull request by muharem**
The chain spec based on previous Westend Collectives chain spec, the only changes are:
- parachain id changed from 1002 to 1001 to align with future Polkadot Collectives 
- latest (v9290) runtime wasm binary 
- nonraw spec file (human readable) format

### CODE REVIEW

**Review by gilescope — APPROVED** [review]
Looks good. Start and end bytes match what I was expecting of the runtime.

**Review by joepetrowski — APPROVED** [review]

**Comment by muharem** [comment]
Bot merge

**Comment by bkchr** [comment]
@muharem the chain spec you added is a not a raw chain spec.

**Comment by muharem** [comment]
> @muharem the chain spec you added is a not a raw chain spec.

yes, the idea was to make it human readable.
should I upload the raw one? can you explain please why we wanna store a raw one?

**Comment by bkchr** [comment]
The human readable chain spec requires the native runtime to be loaded. When you change the native runtime the chain spec can not be loaded anymore. Using the human readable chain spec on the same commit is fine, but the moment something changes it starts to fail to load the chain spec (which is the case on master).

**Comment by muharem** [comment]
> The human readable chain spec requires the native runtime to be loaded. When you change the native runtime the chain spec can not be loaded anymore. Using the human readable chain spec on the same commit is fine, but the moment something changes it starts to fail to load the chain spec (which is the case on master).

https://github.com/paritytech/cumulus/pull/2131

**Pull request merged**
