### PR TITLE
pallets: implement `Default` for `GenesisConfig` in `no_std`

### PR DESCRIPTION
**Pull request by michalkucharczyk**
Implementation of `Default` trait for pallets enabled for `no_std` environments.

This change is follow-up of: https://github.com/paritytech/substrate/pull/14108
It is a step towards: https://github.com/paritytech/substrate/issues/13334

Companion for: paritytech/substrate#14107

### CODE REVIEW

**Comment by michalkucharczyk** [comment]
bot format

**Comment by michalkucharczyk** [comment]
bot fmt

**Comment by michalkucharczyk** [comment]
bot clean

**Review by gilescope — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
bot rebase

**Pull request merged**
