### PR TITLE
Node bump to v0.9.220

### PR DESCRIPTION
**Pull request by chevdor**
See also #1283

### CODE REVIEW

**Review by joepetrowski — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Comment by NukeManDan** [comment]
I assume this should be included in the https://github.com/paritytech/cumulus/tree/polkadot-v0.9.22 as well. Ideally this would be included in the release pipeline for Polkadot, yes?

**Comment by NukeManDan** [comment]
I assume this should be included in the https://github.com/paritytech/cumulus/tree/polkadot-v0.9.22 as well. Ideally this would be included in the release pipeline for Polkadot, yes?

**Comment by chevdor** [comment]
> I assume this should be included in the https://github.com/paritytech/cumulus/tree/polkadot-v0.9.22 as well. Ideally this would be included in the release pipeline for Polkadot, yes?

As soon as merged yes

**Comment by chevdor** [comment]
bot merge

**Pull request merged**
