### PR TITLE
Provisioner polkadot companion

### PR DESCRIPTION
**Pull request by alexgparity**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2110227

**Comment by bkchr** [comment]
Why did you merged the other prs? You are now blocking all other prs with unrelated failures to their prs.

You have the bot to merge these prs for you: https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc

**Review by dmitry-markin — APPROVED** [review]

**Comment by alexgparity** [comment]
> Why did you merged the other prs? You are now blocking all other prs with unrelated failures to their prs.
> 
> You have the bot to merge these prs for you: https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc

The PRs were approved so my monkey brain naturally pushed the merge button. I've now been told about the bot a few times. I still believe if people shouldn't merge using the button, it should be disabled. Will use the bot going forward, of course.

**Comment by ggwpez** [comment]
> I still believe if people shouldn't merge using the button, it should be disabled

There are situations where it is necessary to merge manually, for example here https://github.com/paritytech/substrate/pull/12829#issuecomment-1335799060  
The Companion CI does not check everything, so there are possibilities when you need to bypass it.  

Anyway in most cases it fails for valid reasons and should not be bypassed.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> > Why did you merged the other prs? You are now blocking all other prs with unrelated failures to their prs.
> > You have the bot to merge these prs for you: https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc
> 
> The PRs were approved so my monkey brain naturally pushed the merge button. I've now been told about the bot a few times. I still believe if people shouldn't merge using the button, it should be disabled. Will use the bot going forward, of course.

Thank you :) I mean it is not a big problem especially as we have weekend, just annoying ^^

**Pull request merged**
