### PR TITLE
[Backport] weights from v9320 release branch

### PR DESCRIPTION
**Pull request by EgorPopelyaev**
This PR backports weights applied in the latest release v9320

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2058001

**Review by gilescope — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by EgorPopelyaev** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2066995

**Comment by tonyalaribe** [comment]
bot merge

**Pull request merged**
