### PR TITLE
update substrate & polkadot

### PR DESCRIPTION
**Pull request by xlc**
companion for https://github.com/paritytech/substrate/pull/7778

also updated librocksdb-sys so it compiles on Apple M1

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
Ty

**Comment by bkchr** [comment]
bot merge

**Comment by xlc** [comment]
> sccache: Compile terminated by signal 9
error: could not compile `polkadot-collator`

Looks like out of memory?

**Comment by xlc** [comment]
Yeah the build machine needs a spec bump.

Or fix https://github.com/paritytech/cumulus/issues/446

**Comment by xlc** [comment]
bot merge

**Comment by bkchr** [comment]
> Yeah the build machine needs a spec bump.
> 
> Or fix #446

Maybe someone is working on this :P

**Pull request merged**
