### PR TITLE
improve deps for xcm-emulator

### PR DESCRIPTION
**Pull request by xlc**
So that it doesn't need to pulling cumulus-test-service, which have huge dependencies.

I noticed this when updating Acala and noticed I am building pallet-glutton which I shouldn't.

This is also one of the that I am against mono repo as it is too easy for people to pulling deps from other crates without proper thinking the dependency tree.

There are other offenders such as cumulus-pallet-xcmp-queue depends polkadot-runtime-common which itself is huge. But the proper fix requires a larger refactoring.

### CODE REVIEW

**Review by gilescope — APPROVED** [review]
Totally agree. I'm sure I have the same change on one of my local branches.

**Comment by gilescope** [comment]
bot fmt

**Review by ggwpez — APPROVED** [review]
Yea looks like a good trade-off.

**Comment by gilescope** [comment]
bot merge

**Pull request merged**
