### PR TITLE
Bump substrate (because of failing asset-hub-westend benchmarks)

### PR DESCRIPTION
**Pull request by bkontur**
Relates to: https://github.com/paritytech/cumulus/pull/2846
Relates to: https://github.com/paritytech/cumulus/issues/2806

### CODE REVIEW

**Review by jsidorenko — APPROVED** [review]

**Comment by bkontur** [comment]
bot merge

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3165284

**Comment by bkontur** [comment]
bot help

**Comment by bkontur** [comment]
bot merge

**Pull request merged**
