### PR TITLE
Rename of polkadot-collator to polkadot-parachain

### PR DESCRIPTION
**Pull request by gilescope**
Rename collator bin and make this same code available under the new docker container name.
( backport of https://github.com/paritytech/cumulus/pull/1241 )

### CODE REVIEW

**Comment by bkchr** [comment]
Why is this backported? There will be a new release next week.

**Comment by chevdor** [comment]
Indeed, there is no reason to modify 0.9.19, those releases are out already.

**Comment by gilescope** [comment]
We have nothing currently in docker at `polkadot-parachain:latest` - this could cause trouble for zombinet next week if they start using the new bin name.

**Comment by gilescope** [comment]
@joepetrowski suggested this as a simple solution and I tend to agree with him.

**Comment by gilescope** [comment]
ok let's close this as next version is almost upon us.

**Pull request closed without merging**
