### PR TITLE
Companion for #13701

### PR DESCRIPTION
**Pull request by arkpar**
Companion for https://github.com/paritytech/substrate/pull/13701

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2633425

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2730117

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2730288

**Review by cheme — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by arkpar** [comment]
bot merge

**Pull request merged**
