### PR TITLE
Reorganize/Move Docker scripts

### PR DESCRIPTION
**Pull request by cecton**
I want to do this but I can test as Docker has some issues on my machine...

### CODE REVIEW

**Comment by cecton** [comment]
But it's not super important either so I guess it could stay the way it is now

**Comment by bkchr** [comment]
Did you checked this?

**Comment by cecton** [comment]
No and I can't fix my Docker easily... I will do it at some point. I believe the changes I did are correct but it would be better to actually test

**Comment by cecton** [comment]
Ok I will rebase and merge as-it. If it breaks someone will hate me but I don't think many people use it except you atm...

**Pull request merged**
