### PR TITLE
don't have integration tests in 2 places.

### PR DESCRIPTION
**Pull request by gilescope**
use https://github.com/paritytech/parachains-integration-tests/tree/master/examples as the definitive.

### CODE REVIEW

**Review by ruseinov — APPROVED** [review]

**Comment by NachoPal** [comment]
The idea was to have them in Cumulus to be able to run them with a CI job: https://github.com/paritytech/ci_cd/issues/499

`parachains-integration-tests` was never meant to be the source of truth for the tests.

However, if we are moving away from these tests, to be replaced by this: https://github.com/paritytech/cumulus/issues/2195
then remove them from Cumulus.

**Comment by ruseinov** [comment]
> The idea was to have them in Cumulus to be able to run them with a CI job: [paritytech/ci_cd#499](https://github.com/paritytech/ci_cd/issues/499)
> 
> `parachains-integration-tests` was never meant to be the source of truth for the tests. They are there just as an example of how to use the tool.
> 
> However, if we are moving away from these tests to be replaced by this: #2195, then it makes sense to remove them from Cumulus.

But the truth is that not only those tests ended up being the source of truth, they also come with a better runner!

**Comment by joepetrowski** [comment]
Can close?

**Comment by NachoPal** [comment]
> Can close?

Yes, will keep the tests in Cumulus. Closing it.

**Pull request closed without merging**
