### PR TITLE
Bump polkadot

### PR DESCRIPTION
**Pull request by bkontur**

### CODE REVIEW

**Review by gilescope — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2478617

**Review by joepetrowski — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2478869

**Comment by bkontur** [comment]
waiting for https://github.com/paritytech/cumulus/pull/2245

**Comment by ruseinov** [comment]
bot merge

**Pull request merged**
