### PR TITLE
Companion for substrate#14188 (Add genesis config to Glutton pallet)

### PR DESCRIPTION
**Pull request by NachoPal**
- Companion of https://github.com/paritytech/substrate/pull/14188
- Adding `sudo` to Glutton parachain

### CODE REVIEW

**Comment by NachoPal** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2872777

**Comment by NachoPal** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2879796

**Comment by bkontur** [comment]
@NachoPal 
unrelated, shouldnt we put glutton-kusama to the `.github/pr-custom-review.yml` ?

**Review by bkchr — APPROVED** [review]

**Pull request merged**
