### PR TITLE
Enable asset teleportation on Statemint

### PR DESCRIPTION
**Pull request by KiChjang**

### CODE REVIEW

**Comment by gilescope** [comment]
https://github.com/paritytech/cumulus/pull/912 seems related

**Comment by KiChjang** [comment]
@gilescope You're right, we'll need both #912 and this PR in order for the `teleport_asset` extrinsic to work properly.

**Review by joepetrowski — APPROVED** [review]
Given that this has no effect until Relay Chain governance decides it's OK to send DOT to Statemint, then it's OK for Statemint to send it back as well.

**Comment by joepetrowski** [comment]
Actually, we probably need https://github.com/paritytech/polkadot/issues/4462 in the Relay Chain first.

**Comment by hbulgarini** [comment]
@KiChjang can we close this PR? it seems to be doing the same as #1057 which contains related work for enabling XCM transfers and lift asset creation restrictions.

**Comment by KiChjang** [comment]
Yeah, let's close this.

**Pull request closed without merging**
