### PR TITLE
Add the uniques migration for statemine

### PR DESCRIPTION
**Pull request by kianenigma**
See: https://github.com/paritytech/substrate/pull/10650#discussion_r786932021

fixes https://github.com/paritytech/cumulus/issues/910

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
Thinking out loud: you might say this is now extra effort that we've created by removing migrations from inside the pallet, but to me this is actually the point: I want more people (perhaps forcefully) thinking about what migrations they need to write, and in which chains they need to be applied, and how to label their PRs so that everyone is notified etc.

**Comment by hamidra** [comment]
> Thinking out loud: you might say this is now extra effort that we've created by removing migrations from inside the pallet, but to me this is actually the point: I want more people (perhaps forcefully) thinking about what migrations they need to write, and in which chains they need to be applied, and how to label their PRs so that everyone is notified etc.

Also might be worth to update this [docs](https://docs.substrate.io/how-to-guides/v3/storage-migrations/basics/) to mention the best practices. I guess many people will start from there when writing migrations!

**Comment by kianenigma** [comment]
> 

Good idea: https://github.com/substrate-developer-hub/substrate-docs/issues/780

**Comment by kianenigma** [comment]
Should be green now. @bkchr feel free to merge when ready. Note how I updated substrate and polkadot in the commit messages as well.

**Pull request merged**
