### PR TITLE
Use genesis_state_version param instead of StateVersion::V0

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

related: https://github.com/paritytech/cumulus/pull/1325

### CODE REVIEW

**Comment by koushiro** [comment]
@bkchr  @shawntabrizi PTAL

**Review by bkchr — APPROVED** [review]

**Comment by koushiro** [comment]
@shawntabrizi could you take a look?

**Comment by koushiro** [comment]
@shawntabrizi could you take a look?

**Comment by koushiro** [comment]
@bkchr Is there anyone else who can help review this PR?

**Comment by koushiro** [comment]
@bkchr could you cherry-pick this commit to the `polkadot-v0.9.25` branch?

**Pull request merged**
