### PR TITLE
Companion for #13486

### PR DESCRIPTION
**Pull request by Szegoo**
paritytech/substrate#13486

### CODE REVIEW

**Comment by Szegoo** [comment]
@ggwpez Could you run the bench bot here also?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2464014

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> @ggwpez Could you run the bench bot here also?

For that we will first need to include the Substrate changes here. We update the weight any way per release, so copying the value from Substrate should be fine for now.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2471861

**Comment by jsidorenko** [comment]
bot rebase

**Comment by jsidorenko** [comment]
bot merge

**Pull request merged**
