### PR TITLE
Co #12341: Use `try-runtime` feature

### PR DESCRIPTION
**Pull request by ggwpez**
Companion for Substrate https://github.com/paritytech/substrate/pull/12341

Changes:
- Fix features to make it compile.
- Add dummy command that prints that try-runtime requires a feature, since right now it would not show up in `--help` anymore. That could impede discoverability.

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by ggwpez** [comment]
CI stuck?!

**Comment by bkchr** [comment]
bot rebase

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Comment by dmitry-markin** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
