### PR TITLE
Co #14338: `pallet-glutton`: over-unity consumption

### PR DESCRIPTION
**Pull request by ggwpez**
Companion for https://github.com/paritytech/substrate/pull/14338

Change:
- `Perbill` to `FixedU64`
- Rename `*_percent` to `*_ratio`
- Fix typos

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2976514

**Comment by NachoPal** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2977688

**Comment by NachoPal** [comment]
If the actual spent PoV depends on benchmarked weights. Does it mean we shouldn't regenerate the Weights for [this](https://github.com/paritytech/substrate/pull/14338#issue-1750148007) calculations to remain correct?

**Comment by ggwpez** [comment]
>If the actual spent PoV depends on benchmarked weights. Does it mean we shouldn't regenerate the Weights for https://github.com/paritytech/substrate/pull/14338#issue-1750148007 calculations to remain correct?

Yea I will call the benchbot, thanks for noticing.  
There should be no change, but lets see.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2978703

**Comment by NachoPal** [comment]
> Yea I will call the benchbot, thanks for noticing.

The runtime is using local weights though. If you want to update them you should run the benchbot also here

**Comment by ggwpez** [comment]
> The runtime is using local weights though. If you want to update them you should run the benchbot also here

I hope weights are updated prio to releases anyway?  
But can still do once upstream merged. Only downside is that this will block the Cumulus CI check for 2-3 hours for everyone.

**Comment by ggwpez** [comment]
Maybe I can also diener it and call the bot directly here, will try.

**Comment by NachoPal** [comment]
> I hope weights are updated prior to releases anyway?

Yes, they will be, but we are not waiting for next release to deploy Gluttons, we get the runtime from `master`.

I would just leave the weights as they are.

**Review by NachoPal — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Pull request merged**
