### PR TITLE
companion for #11796

### PR DESCRIPTION
**Pull request by Szegoo**
https://github.com/paritytech/substrate/pull/11796

### CODE REVIEW

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ pallet statemine pallet_uniques  
/cmd queue -c bench-bot $ pallet statemint pallet_uniques  
/cmd queue -c bench-bot $ pallet westmint pallet_uniques

**Review by ggwpez — APPROVED** [review]
Its fine to use the Substrate weights at first.  
They will be re-calculated before each release anyway.  

PS: I think we can still use the bot, lets try.

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=11796 -c bench-bot $ pallet statemint pallet_uniques

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=11796 -c bench-bot $ pallet statemint assets pallet_uniques

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=11796 -c bench-bot $ pallet statemine assets pallet_uniques  
/cmd queue -v PATCH_substrate=11796 -c bench-bot $ pallet westmint assets pallet_uniques

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=11796 -c bench-bot $ pallet westmint assets pallet_uniques

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
