### PR TITLE
companion for #13384

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Review by skunert — APPROVED** [review]

**Review by koute — APPROVED** [review]

**Comment by niklasad1** [comment]
bot rebase

**Comment by niklasad1** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2733917

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2765253

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2765500

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2772319

**Comment by muharem** [comment]
bot rebase

**Comment by muharem** [comment]
@niklasad1 I updated polkadot and substrate deps and pushed the commit, to merge this PR, hope you fine with it.

**Comment by muharem** [comment]
bot merge

**Comment by bkchr** [comment]
@muharem ty! I wanted to do this, but was distracted :see_no_evil:

**Comment by niklasad1** [comment]
> @niklasad1 I updated polkadot and substrate deps and pushed the commit, to merge this PR, hope you fine with it.

oops, sorry I missed that I pushed a commit that fucked the merge.

**Comment by niklasad1** [comment]
bot merge

**Pull request merged**
