### PR TITLE
ci: fix publish-runtimes for parachains containing - in name (v2) (backport of #959)

### PR DESCRIPTION
**Pull request by coderobe**
See https://github.com/paritytech/cumulus/pull/959

### CODE REVIEW

**Comment by coderobe** [comment]
bot merge

**Review by EgorPopelyaev — APPROVED** [review]

**Comment by coderobe** [comment]
bot merge

**Comment by coderobe** [comment]
i've tested the workflow locally with this change and we have a success :sparkles: 

this should be all good to merge :heavy_check_mark:

**Comment by coderobe** [comment]
bot merge

**Pull request merged**
