### PR TITLE
[Revert] Use XCM V3 for initiate_teleport weight calc #2102

### PR DESCRIPTION
**Pull request by EgorPopelyaev**
This PR reverts changes made in #2102 because of https://github.com/paritytech/cumulus/issues/2392

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2601812

**Review by muharem — COMMENTED** [review]
@EgorPopelyaev why we wanna revert?

**Comment by joepetrowski** [comment]
> @EgorPopelyaev why we wanna revert?

Because the message constructed on the Polkadot side uses `All`, which makes this fee equal to `max_assets`. It should be reverted until the Polkadot message uses the `Counted` variant for accurate weight.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2603260

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2608893

**Review by bkontur — APPROVED** [review]

**Review by gilescope — APPROVED** [review]

**Pull request merged**
