### PR TITLE
Add dockerfiles for rococo collator

### PR DESCRIPTION
**Pull request by radupopa2010**

### CODE REVIEW

**Comment by radupopa2010** [comment]
I don't understand why are all other commits included in this PR, I only added 2 dockerfiles.
There are 2 versions of dockerfile for rococo-collator:
 1: using cargo-chef: which is good when you build the image locally, you take advantage of compiling first the dependencies, then the app
 2: using a base image "paritytech/ci-linux:production" which is meant more for a futures build by the CI.

**Comment by bkchr** [comment]
Please clean this up...
You used the completely wrong branch. 

And how will maintain these docker files?

**Comment by bkchr** [comment]
And what is the difference to the already existing docker files?

**Comment by radupopa2010** [comment]
Closing this PR and starting over

**Pull request closed without merging**
