### PR TITLE
Companion for paritytech/substrate#12219

### PR DESCRIPTION
**Pull request by KiChjang**
Companion for paritytech/substrate#12219

Closes #1609.

### CODE REVIEW

**Review by eskimor — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Comment by KiChjang** [comment]
bot merge

**Comment by KiChjang** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
