### PR TITLE
Polkadot companion #6603: Use a `BoundedVec` in `ValidationResult`

### PR DESCRIPTION
**Pull request by mrcnski**
Companion for https://github.com/paritytech/polkadot/pull/6603

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2352023

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2353004

**Review by bkchr — APPROVED** [review]

**Review by s0me0ne-unkn0wn — APPROVED** [review]
Looks good!

**Review by s0me0ne-unkn0wn — APPROVED** [review]
`unwrap()` is okay in tests, but it's still better like this.

**Pull request merged**
