### PR TITLE
Update polkadot 0.9.38

### PR DESCRIPTION
**Pull request by chevdor**
Mainly to bring polkadot#6787 in

### CODE REVIEW

**Comment by chevdor** [comment]
bot merge

**Review by gilescope — APPROVED** [review]
Confirmed that #6787 is in there.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2502293

**Comment by gilescope** [comment]
bot merge

**Pull request merged**
