### PR TITLE
Companion: Remove contracts RPC

### PR DESCRIPTION
**Pull request by athei**
Companion for https://github.com/paritytech/substrate/pull/12358

### CODE REVIEW

**Review by ascjones — APPROVED** [review]

**Review by cmichi — APPROVED** [review]

**Comment by athei** [comment]
bot rebase

**Comment by athei** [comment]
bot rebase

**Comment by athei** [comment]
The error seems to be unrelated to my changes:
```
The panic is expected if runtime weights are not correct
```

**Review by ggwpez — APPROVED** [review]
Can we merge this? Its blocking the Substrate CI.

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
