### PR TITLE
AssetHubs - split weights for pallet_assets

### PR DESCRIPTION
**Pull request by bkontur**
Relates to: https://github.com/paritytech/cumulus/issues/2727

Closes: https://github.com/paritytech/cumulus/issues/2732

### CODE REVIEW

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-kusama assets pallet_assets
bot bench $ pallet asset-hub-westend assets pallet_assets
bot bench $ pallet asset-hub-polkadot assets pallet_assets

**Review by joepetrowski — APPROVED** [review]

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-kusama assets pallet_assets
bot bench $ pallet asset-hub-westend assets pallet_assets
bot bench $ pallet asset-hub-polkadot assets pallet_assets

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-kusama assets pallet_assets
bot bench $ pallet asset-hub-westend assets pallet_assets
bot bench $ pallet asset-hub-polkadot assets pallet_assets

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak-fatal-remote-github $ pallet asset-hub-kusama assets pallet_assets

**Comment by mordamax** [comment]
@bkontur im sorry, i accidentally closed this PR instead of mine

**Review by gilescope — APPROVED** [review]
LGTM

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-westend assets pallet_assets

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-polkadot assets pallet_assets

**Review by ggwpez — APPROVED** [review]
Great!  
There should also be an error thrown now if multiple instance results overwrite each other https://github.com/paritytech/substrate/pull/14352

**Comment by bkontur** [comment]
> Great! There should also be an error thrown now if multiple instance results overwrite each other [paritytech/substrate#14352](https://github.com/paritytech/substrate/pull/14352)

it depends on how you choose `--output` argument:
- if it is set as **directory**  e.g. `--output=../weights`, then there is no override and no error, because files are automatically generated with pallet instance suffix, which ok
- if you set it like **file** `--output=../weights/pallet_assets.rs`, then there is that error you pointed to

also thats why I changed it here as **directory** https://github.com/paritytech/command-bot-scripts/pull/34/files#diff-69b88c8de5896ad805e152e37b23b17b9b55e30da6674ba2bdd52c27a482145eL99-R70

**Comment by ggwpez** [comment]
> also thats why I changed it here as **directory** https://github.com/paritytech/command-bot-scripts/pull/34/files#diff-69b88c8de5896ad805e152e37b23b17b9b55e30da6674ba2bdd52c27a482145eL99-R70

Yes good. I had the feeling that in some spots we are silently overwriting this without noticing - therefore the change to error out in that case.

**Review by gavofyork — CHANGES_REQUESTED** [review]
Please save us from the utterly awful naming.

`pallet_assets_local` and `pallet_assets_remote`.

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-polkadot assets pallet_assets

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-kusama assets pallet_assets
bot bench $ pallet asset-hub-westend assets pallet_assets

**Comment by bkontur** [comment]
> > `pallet_assets_assets`
> 
> Please save us from the utterly awful naming.
> 
> `pallet_assets_local` and `pallet_assets_remote` would be acceptable.

@gavofyork 

changed to `pallet_assets_local.rs` / `pallet_assets_remote.rs`

**Review by gavofyork — APPROVED** [review]

**Comment by gavofyork** [comment]
> > > `pallet_assets_assets`
> > 
> > 
> > Please save us from the utterly awful naming.
> > `pallet_assets_local` and `pallet_assets_remote` would be acceptable.
> 
> @gavofyork
> 
> changed to `pallet_assets_local.rs` / `pallet_assets_remote.rs`

Actually, `pallet_assets_foreign` would work better...

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-kusama assets pallet_assets
bot bench $ pallet asset-hub-westend assets pallet_assets
bot bench $ pallet asset-hub-polkadot assets pallet_assets

**Comment by bkontur** [comment]
bot merge

**Pull request merged**
