### PR TITLE
[ci] fix pipeline for polkadot-v branches

### PR DESCRIPTION
**Pull request by alvicsam**
Gitlab pipeline didn't work for `polakdot-v*` branches. PR fixes this

### CODE REVIEW

**Review by sergejparity — APPROVED** [review]

**Review by chevdor — APPROVED** [review]

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
Currently tests are failing, created an issue https://github.com/paritytech/cumulus/issues/1520

**Review by coderobe — APPROVED** [review]

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Pull request merged**
