### PR TITLE
New weights

### PR DESCRIPTION
**Pull request by bkontur**

### CODE REVIEW

**Comment by bkontur** [comment]
/cmd queue -c bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_grandpa::wococo

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_grandpa::wococo

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2519970

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_grandpa::wococo

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_grandpa::rococo

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_parachains::wococo

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_parachains::rococo

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_messages::wococo

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2524851

**Comment by bkontur** [comment]
bot bench $ pallet bridge-hub-rococo bridge-hubs pallet_bridge_grandpa

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2525404

**Review by svyatonik — APPROVED** [review]
Almost all weights are x5-x10 or so. I guess because of running on `bkontur-ThinkPad-P14s-Gen-2i` instead of dedicated benchmarks machine. We are going to actually update weights before next runtime upgrade, right? Just to have something close to what we'll use in Polkadot <> Jusama bridge hub

**Comment by bkontur** [comment]
> Almost all weights are x5-x10 or so. I guess because of running on `bkontur-ThinkPad-P14s-Gen-2i` instead of dedicated benchmarks machine. We are going to actually update weights before next runtime upgrade, right? Just to have something close to what we'll use in Polkadot <> Jusama bridge hub

yes, exactly, I just wanted to remove `from_ref_time` because CI pipelines dont work with deprecated stuff,
weights are regenerated before every release

**Pull request merged**
