### PR TITLE
[companion] Get rid of `Peerset` compatibility layer

### PR DESCRIPTION
**Pull request by dmitry-markin**
Companion for https://github.com/paritytech/substrate/pull/14337.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2996925

**Review by altonen — APPROVED** [review]

**Review by kpp — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3236411

**Review by skunert — APPROVED** [review]

**Review by melekes — APPROVED** [review]
👍

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3262525

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3316375

**Comment by dmitry-markin** [comment]
bot merge

**Comment by dmitry-markin** [comment]
bot merge

**Comment by dmitry-markin** [comment]
bot merge

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3319563

**Comment by dmitry-markin** [comment]
Set this PR as a companion for https://github.com/paritytech/polkadot/pull/7572, otherwise Cumulus CI is stuck.

**Pull request merged**
