### PR TITLE
update weights for v9220

### PR DESCRIPTION
**Pull request by gilescope**
transfer ownership of uniques cheaper.
batch all now looking a bit expensive compared to batch. 

no big changes.

### CODE REVIEW

**Review by NachoPal — APPROVED** [review]
LGTM

**Review by joepetrowski — APPROVED** [review]

**Comment by ggwpez** [comment]
I'm beta testing a new [swc-web](https://weights.tasty.limo:8443/compare?old=93a01eda224f76448a52f9f5b513c5f92987470a&new=032b334d5e7f56d7bb4cd48d9907b175d37439ea&threshold=5&unit=time&repo=cumulus&path_pattern=**%2Fweights%2F*.rs&method=base&ignore_errors=true) version. Feedback welcome!

**Review by ggwpez — APPROVED** [review]

**Comment by chevdor** [comment]
FYI try to test using [Oliver's tool](https://weights.tasty.limo/compare?old=parachains-v9.0.0&new=giles-update-weights-9220&threshold=30&unit=weight&repo=cumulus&path_pattern=polkadot-parachains/runtimes%2F**%2Fsrc%2Fweights%2F**%2F*.rs&method=worst&ignore_errors=true)

**Comment by gilescope** [comment]
bot merge

**Comment by ggwpez** [comment]
> FYI try to test using [Oliver's tool](https://weights.tasty.limo/compare?old=parachains-v9.0.0&new=giles-update-weights-9220&threshold=30&unit=weight&repo=cumulus&path_pattern=polkadot-parachains/runtimes%2F**%2Fsrc%2Fweights%2F**%2F*.rs&method=worst&ignore_errors=true) => `revspec 'giles-update-weights-9220' not found`

Thanks for the hint! Somehow the docker and the git autoupdate script mess up sometimes.  
Need to find a better solution...  
Its updated now.  
I personally rather use commit hashes, since otherwise it could happen that it has a stale branch or tag.

**Comment by chevdor** [comment]
I prefer using tags or branches as this is what CI will end up using. Thansk for the fix.

I am surprised to see 0 results however, even with [1% threshold](https://weights.tasty.limo/compare?old=parachains-v9.0.0&new=master&threshold=1&unit=weight&repo=cumulus&path_pattern=polkadot-parachains%2Fruntimes%2F**%2Fsrc%2Fweights%2F**%2F*.rs&method=worst&ignore_errors=false).

**Comment by ggwpez** [comment]
> I prefer using tags or branches as this is what CI will end up using. Thansk for the fix.

Okay fair enough. Still need to figure our a way to do this more reliably as it can currently spit out some 'git checkout' errors.

> I am surprised to see 0 results however, even with [1% threshold](https://weights.tasty.limo/compare?old=parachains-v9.0.0&new=master&threshold=1&unit=weight&repo=cumulus&path_pattern=polkadot-parachains%2Fruntimes%2F**%2Fsrc%2Fweights%2F**%2F*.rs&method=worst&ignore_errors=false).

Yea the folder is incorrect, there are no changes in `polkadot-parachains/runtimes/**/src/weights/**/*.rs`.   
Rather use `parachains/runtimes/**/src/weights/**/*.rs` or more generally `**/weights/*.rs`.

**Pull request merged**
