### PR TITLE
Companion: restructure macro related exports

### PR DESCRIPTION
**Pull request by juangirini**
Restructure `frame_benchmarking` and `frame_support` macro related exports

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Comment by juangirini** [comment]
bot rebase

**Review by kpp — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3406314

**Review by svyatonik — APPROVED** [review]

**Review by bkontur — APPROVED** [review]

**Comment by juangirini** [comment]
bot rebase

**Review by ordian — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by juangirini** [comment]
bot merge

**Pull request merged**
