### PR TITLE
fmt

### PR DESCRIPTION
**Pull request by chevdor**
Fix fmt issues

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
What happened to the formatting check action?

**Review by ggwpez — APPROVED** [review]

**Comment by chevdor** [comment]
The fmt check was removed from GH a while back via https://github.com/paritytech/cumulus/pull/1562/files and added to Gitlab. @alvicsam it looks like there may be an issue in the Gitlab CI: it does not pickup fmt issues.

**Comment by chevdor** [comment]
I opened an issue to track the CI problem: https://github.com/paritytech/cumulus/issues/1732

**Comment by alvicsam** [comment]
It's my fault, I removed auto-fmt because of the forum post and forgot to return the GHA back

**Pull request merged**
