### PR TITLE
Make zombienet tests required

### PR DESCRIPTION
**Pull request by skunert**
Zombienet tests are still allowed to fail. Since the other tests have been removed for a while, let's make them mandatory.

### CODE REVIEW

**Review by EgorPopelyaev — APPROVED** [review]

**Review by alvicsam — APPROVED** [review]
Just want to mention that it doesn't make them `Required` in GitHub.

**Comment by skunert** [comment]
> Just want to mention that it doesn't make them `Required` in GitHub.

Okay, I thought this would make them required here, what do I need to do to make them required for PRs to merge?

**Review by davxy — APPROVED** [review]

**Comment by pepoviola** [comment]
bot rebase

**Comment by pepoviola** [comment]
@skunert I just rebase to update the zombienet version in this pr.
Thanks!

**Pull request merged**
