### PR TITLE
Prevent name clash with Substrate Pallet Template

### PR DESCRIPTION
**Pull request by ggwpez**
Renamed `pallet-template` to `pallet-parachain-template` to avoid name clashes with Substrate once we do the monorepo.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2793006

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2793322

**Review by bkchr — CHANGES_REQUESTED** [review]
The point why we have this pallet there is to have the template ready all the time. We will also not merge this into the general frame repo.

The solution here is to just change the name of the crate

**Comment by ggwpez** [comment]
> The solution here is to just change the name of the crate

Yea i did that before, but then it is named `cumulus-pallet-template`, and when someone forks it outside of the cumulus repo, then the name does not make sense.  
So maybe `pallet-parachain-template`?

**Review by bkchr — APPROVED** [review]

**Review by joepetrowski — APPROVED** [review]

**Pull request merged**
