### PR TITLE
Update weights with VM runners

### PR DESCRIPTION
**Pull request by oleg-plakida**
- Update weights using VM instances
 - Change runner tag for weights ci job to weights-vm

cc: paritytech/ci_cd#697

### CODE REVIEW

**Comment by oleg-plakida** [comment]
bot help

**Comment by oleg-plakida** [comment]
bot bench-vm $ all

**Comment by oleg-plakida** [comment]
bot bench-vm -v PIPELINE_SCRIPTS_REF=mak-remove-p-cumulus-all $ all

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot bench-vm -v PIPELINE_SCRIPTS_REF=mak-remove-p-cumulus-all $ all

**Comment by oleg-plakida** [comment]
bot bench-vm $ all

**Comment by bkontur** [comment]
when merged https://github.com/paritytech/cumulus/pull/2741
pallet_assets should work

**Comment by bkontur** [comment]
@ggwpez 
bump substrate is merged,
but lets wait for this: https://github.com/paritytech/cumulus/issues/2732 and jobs here: https://github.com/paritytech/cumulus/pull/2741

because, it should generate to separate files for two instances of pallet_assets

**Comment by bkontur** [comment]
bot rebase

**Comment by bkontur** [comment]
bot bench-vm $ all

**Comment by oleg-plakida** [comment]
> bot bench-vm $ all

I see that there is a recent change in cumulus bench bot script which lead to this error.
https://github.com/paritytech/command-bot-scripts/blame/main/commands/bench/lib/bench-all-cumulus.sh

**Comment by oleg-plakida** [comment]
> @bkontur Command `"$PIPELINE_SCRIPTS_DIR/commands/bench-vm/bench-vm.sh" all` has finished. Result: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3034970 has finished. If any artifacts were generated, you can download them from https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3034970/artifacts/download.

paritytech/command-bot-scripts/pull#38

**Comment by oleg-plakida** [comment]
bot bench-vm $ all

**Comment by oleg-plakida** [comment]
@bkontur Something's failed...

**Review by EgorPopelyaev — APPROVED** [review]

**Comment by bkontur** [comment]
bot bench $ pallet asset-hub-kusama assets frame_system

**Comment by bkontur** [comment]
@oleg-plakida 
I investigated that a little bit here https://github.com/paritytech/cumulus/issues/2765
I know how and what to fix, but it takes some time

as a temporary fix, we could skip frame_system pallet from benchmarking,
e.g. before running the benchmark https://github.com/paritytech/command-bot-scripts/blob/main/commands/bench/lib/bench-all-cumulus.sh#L56
add something like:
```
    if [[ "$pallet" == "frame_system" ]]; then
      echo "TODO: (https://github.com/paritytech/cumulus/issues/2765) temporary skipping frame_system pallet"
      continue
    fi
```

wdyt?

**Comment by oleg-plakida** [comment]
> @oleg-plakida I investigated that a little bit here #2765 I know how and what to fix, but it takes some time
> 
> as a temporary fix, we could skip frame_system pallet from benchmarking, e.g. before running the benchmark https://github.com/paritytech/command-bot-scripts/blob/main/commands/bench/lib/bench-all-cumulus.sh#L56 add something like:
> 
> ```
>     if [[ "$pallet" == "frame_system" ]]; then
>       echo "TODO: (https://github.com/paritytech/cumulus/issues/2765) temporary skipping frame_system pallet"
>       continue
>     fi
> ```
> 
> wdyt?

I would rather wait for solid fix. How do you think, how long will it take?

**Comment by ggwpez** [comment]
The `set_code` benchmark was added quite recently, so we lived all the time without it.  
Only downside is that it also skips the other benchmarks of the pallet.

**Comment by bkontur** [comment]
bot rebase

**Comment by bkontur** [comment]
bot bench-vm $ all

**Comment by bkontur** [comment]
bot rebase

**Comment by oleg-plakida** [comment]
bot bench $ all

**Comment by oleg-plakida** [comment]
> bot bench-vm $ all

VM runners are now default for `bot bench` command.

**Comment by bkontur** [comment]
> > bot bench-vm $ all
> 
> VM runners are now default for `bot bench` command.

aha, ok, cool, thank you, I've just read your message in element :)

**Comment by bkontur** [comment]
bot rebase

**Comment by bkontur** [comment]
bot bench $ all

**Comment by bkontur** [comment]
bot rebase

**Comment by bkontur** [comment]
@oleg-plakida @ggwpez 
finally, all cumulus benchmarks are fixed,
so now this should work

**Review by chevdor — APPROVED** [review]

**Comment by oleg-plakida** [comment]
bot bench $ all

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3250422

**Comment by bkontur** [comment]
@vstam1 @franciscoaguirre 
guys, was there any recent change in pallet_xcm benchmarks that moved `initiate_reserve_withdraw/reserve_asset_deposited` from `pallet_xcm_benchmarks_generic.rs` to file `pallet_xcm_benchmarks_fungible.rs` ?

**Comment by bkontur** [comment]
> @vstam1 @franciscoaguirre guys, was there any recent change in pallet_xcm benchmarks that moved `initiate_reserve_withdraw/reserve_asset_deposited` from `pallet_xcm_benchmarks_generic.rs` to file `pallet_xcm_benchmarks_fungible.rs` ?
> 
> aha, ok, I see:
> 
> ```
> e628e48671 ("Change Fixed to WeightInfoBounds for Polkadot (#7077)", 2023-07-19)
> ```

will be fixed here: https://github.com/paritytech/cumulus/pull/2934

**Review by sergejparity — APPROVED** [review]

**Comment by bkontur** [comment]
bot bench $ all

**Comment by oleg-plakida** [comment]
bot bench-all cumulus

**Pull request merged**
