### PR TITLE
Companion for Substrate 12307

### PR DESCRIPTION
**Pull request by Dinonard**
Companion for https://github.com/paritytech/substrate/pull/12307

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by joepetrowski — APPROVED** [review]

**Review by jsidorenko — APPROVED** [review]

**Review by tonyalaribe — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Comment by ggwpez** [comment]
Please merge in master and do a `cargo update -p sp-io` @Dinonard   
I tried it manually but do not have permission. This works with all other MRs and Orgs that open MRs here…

**Comment by Dinonard** [comment]
@ggwpez should be done.

I did prepare a new PR after the discussion in `substrate` PR. The new one was made of my personal `cumulus` fork and there I had the option to allow edit from maintainers. So it must be bug with the organization, as Hoon pointed out there.

Really sorry for the inconvenience! Appreciate your time and support! :pray:

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
> I did prepare a new PR after the discussion in substrate PR. The new one was made of my personal cumulus fork and there I had the option to allow edit from maintainers. So it must be bug with the organization, as Hoon pointed out there.

Yea I saw it. But the problem are the approvals. As soon as you got them, you dont want to loose them by opening a new MR :wink: 

> Really sorry for the inconvenience! Appreciate your time and support! pray  

No problem :smile:

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1

**Pull request merged**
