### PR TITLE
(do-not-merge) gav xcm v3 bench

### PR DESCRIPTION
**Pull request by bkontur**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2129525

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2130161

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2130357

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2132279

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2132481

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2134344

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2135346

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2135805

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet westmint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::generic

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2137438

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemint assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2138142

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet westmint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet collectives-polkadot collectives pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet bridge-hub-kusama bridge-hubs pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2138497

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm westmint assets pallet_xcm_benchmarks::generic

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2138613

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2138804

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet collectives-polkadot collectives pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet bridge-hub-kusama bridge-hubs pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2144211

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2145945

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2152930

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2153264

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible

**Review by KiChjang — APPROVED** [review]

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm westmint assets pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet westmint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet bridge-hub-kusama bridge-hubs pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2188270

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet westmint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemint assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2188346

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemint assets pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2188800

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm
/cmd queue -c bench-bot $ pallet westmint assets pallet_xcm
/cmd queue -c bench-bot $ pallet statemint assets pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet collectives-polkadot collectives pallet_xcm

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ pallet bridge-hub-kusama bridge-hubs pallet_xcm
/cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_xcm
/cmd queue -c bench-bot $ xcm bridge-hub-kusama bridge-hubs pallet_xcm_benchmarks::generic

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm bridge-hub-kusama bridge-hubs pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
/cmd queue -c bench-bot $ xcm bridge-hub-rococo bridge-hubs pallet_xcm_benchmarks::generic
/cmd queue -c bench-bot $ xcm bridge-hub-rococo bridge-hubs pallet_xcm_benchmarks::fungible

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2213707

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2213953

**Pull request closed without merging**
