### PR TITLE
Rename .feature extension to .zndsl

### PR DESCRIPTION
**Pull request by wirednkod**
For alignment purposes (and in order to finalize [this issue](https://github.com/paritytech/zombienet/issues/744) in ZombieNet repo, its preferable to rename all `.feature` files to `.zndsl` which is the preferable extension for test configs of zombienet

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Comment by tdimitrov** [comment]
Looks good. Will the CI still execute them after the rename (I've got no idea if it relies on the filenames).

**Review by tdimitrov — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Comment by wirednkod** [comment]
> Looks good. Will the CI still execute them after the rename (I've got no idea if it relies on the filenames).

Good catch. I see [here](https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2418614#L42) that the `.zndsl` is used, though [here](https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2418614#L68) `.feature` is mentioned. I'm not sure where to change that though

**Comment by ggwpez** [comment]
https://github.com/paritytech/cumulus/blob/1faed8b0f0ac2d3b49cc74d13846a0c04b5c61b5/scripts/ci/gitlab/pipeline/zombienet.yml#L53 for example

**Comment by pepoviola** [comment]
Yes, you need to change the filename in the pipeline definition.

Thanks!

**Comment by wirednkod** [comment]
> https://github.com/paritytech/cumulus/blob/1faed8b0f0ac2d3b49cc74d13846a0c04b5c61b5/scripts/ci/gitlab/pipeline/zombienet.yml#L53
> for example

Thank you so much. Will push the change now!

**Review by sergejparity — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
