### PR TITLE
Add Rococo <> Wococo integrity tests

### PR DESCRIPTION
**Pull request by serban300**
Fixes: https://github.com/paritytech/parity-bridges-common/issues/1672

Posting this PR as a draft for the moment because of the issues described [here](https://github.com/paritytech/parity-bridges-common/issues/1672#issuecomment-1344089520).

### CODE REVIEW

**Comment by svyatonik** [comment]
@serban300 can you also, please, add weights tests here, when you have a spare minute. Something like: https://github.com/paritytech/parity-bridges-common/blob/master/bin/rialto/runtime/src/millau_messages.rs#L174-L203 . They'll detect situations when something wrong is with our weights. Thank you!

**Comment by serban300** [comment]
> @serban300 can you also, please, add weights tests here, when you have a spare minute. Something like: https://github.com/paritytech/parity-bridges-common/blob/master/bin/rialto/runtime/src/millau_messages.rs#L174-L203 . They'll detect situations when something wrong is with our weights. Thank you!

Sure, will do. Thanks for pointing this out !

**Comment by serban300** [comment]
> > @serban300 can you also, please, add weights tests here, when you have a spare minute. Something like: https://github.com/paritytech/parity-bridges-common/blob/master/bin/rialto/runtime/src/millau_messages.rs#L174-L203 . They'll detect situations when something wrong is with our weights. Thank you!
> 
> Sure, will do. Thanks for pointing this out !

Done

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2256244

**Comment by serban300** [comment]
TODO: Add integrity tests for the signed extensions after the bridges subtree is updated to the latest version. 

See: https://github.com/paritytech/parity-bridges-common/pull/1780

**Comment by bkontur** [comment]
@serban300 
please, update this, `bridge-hub-rococo-wococo` was moved with actual master-like bridges stuff without patches...

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2285295

**Comment by serban300** [comment]
> @serban300 please, update this, `bridge-hub-rococo-wococo` was moved with actual master-like bridges stuff without patches...

@bkontur thanks ! I updated the PR and added the test for signed extensions. However we still need the backport in `parity-bridges-common` for the `InboundPayload` change in order to have this PR ready for review.

**Comment by bkontur** [comment]
> > @serban300 please, update this, `bridge-hub-rococo-wococo` was moved with actual master-like bridges stuff without patches...
> 
> @bkontur thanks ! I updated the PR and added the test for signed extensions. However we still need the backport in `parity-bridges-common` for the `InboundPayload` change in order to have this PR ready for review.

@serban300 
I updated bridges repo subtree with latest bridges master,
do you mean because of that `EXTRA_STORAGE_PROOF_SIZE` ?

**Comment by serban300** [comment]
> @serban300 I updated bridges repo subtree with latest bridges master, do you mean because of that `EXTRA_STORAGE_PROOF_SIZE` ?

@bkontur I mean the first point from this comment: https://github.com/paritytech/parity-bridges-common/issues/1672#issuecomment-1344089520

The integrity tests expects the type of `InboundPayload` to be `FromBridgedChainMessagePayload`, while in cumulus it is `XcmAsPlainPayload`. Do you plan to backport this change in to `parity-bridges-common` ? If not we should see if we can adapt the test.

**Comment by serban300** [comment]
The PR is ready for review

**Review by bkontur — APPROVED** [review]
@serban300 
very cool, thank you :)

we probably should not touch `bridges` subdirectory here because of avoiding conflicts when doing `git subtree update`, probably backporting changes from bridges repo is ok, I dont know, we will see.[ But this is very small change, so no problem.
I have some script for updating subtree and Slava also prepared something, we need to just "merge it" and find some common way/process

**Pull request merged**
