### PR TITLE
Move parachain inherent data into its own crate

### PR DESCRIPTION
**Pull request by bkchr**
This renames and moves the `SystemInherentData` into its own crate.
The struct is now called `ParachainInherentData`. Besides moving the
struct, this also moves the code for creating this struct into this crate.

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
Why doesn't this inherent have a data provider that implements `ProvideInherentData`? https://crates.parity.io/sp_inherents/trait.ProvideInherentData.html I always wondered this.

**Comment by bkchr** [comment]
This is currently not possible, but comes in the future.

**Review by pepyakin — APPROVED** [review]
That's a good one!

**Comment by JNhua** [comment]
It makes build failed. 
```bash
error[E0277]: the trait bound `<impl Backend<PBlock> as sc_client_api::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, OpaqueExtrinsic>>>::State: StateBackend<BlakeTwo256>` is not satisfied
   --> primitives/parachain-inherent/src/client_side.rs:102:26
    |
102 |     polkadot_backend: &impl Backend<PBlock>,
    |                             ^^^^^^^^^^^^^^^ the trait `StateBackend<BlakeTwo256>` is not implemented for `<impl Backend<PBlock> as sc_client_api::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, OpaqueExtrinsic>>>::State`
    | 
   ::: /Users/jenner/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/api/src/backend.rs:404:17
    |
404 |     type State: StateBackend<HashFor<Block>> + Send;
    |                 ---------------------------- required by this bound in `sc_client_api::Backend`
    |
help: introduce a type parameter with a trait bound instead of using `impl Trait`
    |
101 | fn collect_relay_storage_proof<B: Backend<PBlock>>(
102 |     polkadot_backend: &impl Backend<PBlock>,
103 |     para_id: ParaId,
104 |     relay_parent: PHash,
105 | ) -> Option<sp_state_machine::StorageProof> where <B as sc_client_api::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, OpaqueExtrinsic>>>::State: StateBackend<BlakeTwo256> {
    |

error[E0277]: the trait bound `<impl Backend<PBlock> as sc_client_api::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, OpaqueExtrinsic>>>::State: StateBackend<BlakeTwo256>` is not satisfied
   --> primitives/parachain-inherent/src/client_side.rs:205:27
    |
205 |         polkadot_backend: &impl Backend<PBlock>,
    |                                 ^^^^^^^^^^^^^^^ the trait `StateBackend<BlakeTwo256>` is not implemented for `<impl Backend<PBlock> as sc_client_api::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, OpaqueExtrinsic>>>::State`
    | 
   ::: /Users/jenner/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/api/src/backend.rs:404:17
    |
404 |     type State: StateBackend<HashFor<Block>> + Send;
    |                 ---------------------------- required by this bound in `sc_client_api::Backend`
    |
help: introduce a type parameter with a trait bound instead of using `impl Trait`
    |
202 |     pub fn create_at<PClient, B: Backend<PBlock>>(
203 |         relay_parent: PHash,
204 |         polkadot_client: &PClient,
205 |         polkadot_backend: &impl Backend<PBlock>,
206 |         validation_data: &PersistedValidationData,
207 |         para_id: ParaId,
  ...

error: aborting due to 2 previous errors

```

**Comment by bkchr** [comment]
@JNhua as you see, the CI was green and it also compiled for me locally in multiple runs. Please update your compiler.

**Pull request merged**
