### PR TITLE
BlockId removal: refactor: Finalizer

### PR DESCRIPTION
**Pull request by michalkucharczyk**
It changes the arguments of methods of `Finalizer` trait from: block:
`BlockId<Block>` to: hash: `&Block::Hash`

This PR is part of BlockId::Number refactoring analysis (paritytech/substrate#11292)

Companion for: paritytech/substrate#12528

### CODE REVIEW

**Review by davxy — APPROVED** [review]

**Review by dmitry-markin — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
bot merge

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
bot merge

**Pull request merged**
