### PR TITLE
rename polkadot-parachain package to avoid name clash

### PR DESCRIPTION
**Pull request by gilescope**
There's a polkdot-parachain crate in polkadot. We can rename the bin crate to be a different package while keeping the bin name the same.

This tides up the lock file so that it does not have to specify a version number to distinguish between the two.

### CODE REVIEW

**Review by ruseinov — APPROVED** [review]

**Comment by gilescope** [comment]
Please wait till Chevor gives the nod before we merge this.

**Review by chevdor — APPROVED** [review]
I checked in our `rel` scripts and I don't think we use this value so we should be fine with that change.

**Comment by bkchr** [comment]
bot rebase

**Comment by bkchr** [comment]
bot rebase

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
