### PR TITLE
[Substrate Companion] Upgrade to libp2p 0.51.3

### PR DESCRIPTION
**Pull request by melekes**
Polkadot companion: https://github.com/paritytech/polkadot/pull/7000

PR: https://github.com/paritytech/substrate/pull/13587

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by dmitry-markin — APPROVED** [review]

**Review by altonen — APPROVED** [review]

**Comment by melekes** [comment]
bot rebase

**Review by kpp — APPROVED** [review]

**Comment by melekes** [comment]
bot rebase

**Comment by melekes** [comment]
bot rebase

**Comment by melekes** [comment]
bot rebase

**Comment by melekes** [comment]
bot merge

**Pull request merged**
