### PR TITLE
Remove `as_derivative` from `SafeCallFilter`

### PR DESCRIPTION
**Pull request by joepetrowski**

### CODE REVIEW

**Comment by joepetrowski** [comment]
bot rebase

**Review by KiChjang — APPROVED** [review]

**Comment by xlc** [comment]
any explanations?

**Comment by joepetrowski** [comment]
> any explanations?

It should never have been there:

```rust
/// Calls that are allowed through this filter must:
...
/// 2. Cannot lead to another call being made;
```

**Comment by xlc** [comment]
I still don't understand the rule

https://github.com/paritytech/polkadot/pull/7080#discussion_r1172849109

**Comment by joepetrowski** [comment]
Do you use this on parachains or only the Relay?

**Comment by xlc** [comment]
this doesn’t impact us currently it is just me unsure about the rules

**Review by gilescope — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
