### PR TITLE
Prepare `Canvas` for redeployment on rococo

### PR DESCRIPTION
**Pull request by athei**
I built the current runtime with the `production` profile and generated the chainspec from it. Also change the code to use this chainspec when `--chain canvas-rococo` is used.

### CODE REVIEW

**Comment by cmichi** [comment]
Why do the binary files need to be committed to this repo?

**Comment by athei** [comment]
They don't. The only file we need to commit is `canvas-rococo.json`. The rest can be generated from it. I could upload it somewhere else to not bloat the repo further. I figured I just do what the other chains did and just commit it.

**Comment by athei** [comment]
Removed those files and forced pushed. Then they won't clutter the history.

**Review by cmichi — APPROVED** [review]

**Review by ascjones — APPROVED** [review]

**Comment by athei** [comment]
bot merge

**Pull request merged**
