### PR TITLE
Try-runtime proper return types

### PR DESCRIPTION
**Pull request by Szegoo**
Companion for: https://github.com/paritytech/substrate/pull/13993

Polkadot companion: https://github.com/paritytech/polkadot/pull/7146

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]

**Comment by liamaharon** [comment]
Hey @Szegoo it seems the processbot had trouble updating this companion.

Could you please run `cargo update -p sp-io` on this branch and commit the updated `Cargo.lock`?

**Comment by Szegoo** [comment]
@liamaharon Should be good now :+1:

**Comment by liamaharon** [comment]
@Szegoo looks like one was missed: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2877887

**Comment by liamaharon** [comment]
@Szegoo please do the same for `polkadot` 🙏: `cargo update -p pallet-xcm`

**Comment by Szegoo** [comment]
@liamaharon I didn't miss it on Polkadot, just as you said I had to run `cargo update -p pallet-xcm`

**Pull request merged**
