### PR TITLE
Companion for substrate#13565

### PR DESCRIPTION
**Pull request by agryaznov**
This is a companion PR for https://github.com/paritytech/substrate/pull/13565

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2508818

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2632994

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2726930

**Review by pgherveou — APPROVED** [review]

**Review by xermicus — APPROVED** [review]

**Review by juangirini — APPROVED** [review]

**Comment by agryaznov** [comment]
bot merge

**Comment by agryaznov** [comment]
bot merge

**Pull request merged**
