### PR TITLE
Remove All Assets and Uniques from `NonTransfer` Proxy

### PR DESCRIPTION
**Pull request by shawntabrizi**
Given the nature of the Assets and Uniques pallet, it seems very sensible to disable all access to this pallets from the `NonTransfer` proxy.

Combinations of calls like `mint` and `burn` can be used to emulate transfer behaviors, and who knows what new functions will be added.

Given that we have explicit Proxies for `AssetOwner` and `AssetManager`, which specifically handle management of these pallets, I see little reason for `NonTransfer` proxy to have this risk.

Fixes: https://github.com/paritytech/srlabs_findings/issues/91

### CODE REVIEW

**Comment by xlc** [comment]
I am thinking if it make sense to introduce an event based proxy filtering mechanism. i.e. fail the transaction if a specific event is emitted.

**Comment by shawntabrizi** [comment]
@xlc would only work for transactional extrinsics?

**Comment by xlc** [comment]
Right. So that't depends on making everything `transactional` first.
Another way could be annotate each calls with tags and filter based on whitelist / blacklist of the tags. I guess this won't happen though... But the current proxy filter is really error prone.

**Review by bkchr — APPROVED** [review]
Unique is not in statemint and westmint?

**Comment by shawntabrizi** [comment]
@bkchr nope. should it be?

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
